name: Android CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: npm install
      run: cd react-native-app && npm install

    - name: Make Gradlew Executable
      run: cd react-native-app/android && chmod +x ./gradlew
    
    - name: Generate App APK
      run: |
        cd react-native-app/android && ./gradlew bundleRelease --no-daemon

    - name: 'Upload APK file'
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: react-native-app/android/app/build/outputs/bundle/release/app-release.apk
        retention-days: 5